from model import RationalLLM
from utils import get_response, get_boolean_completion
from BeliefNet import BeliefNetwork
from main import prompt_to_output, prompt_to_output_test

rationalLLM = RationalLLM()

texts = ['Eating meat causes cancer',
'Brexit would not have passed if the entire population had voted',
'The chicken came before the egg']

caches = [{'nodes': ['eating meat', 'causes cancer'], 'factors': ['cultural and societal norms', 'personal taste preferences', 'nutritional benefits', 'convenience and availability', 'economic factors', 'religious or ethical beliefs', 'environmental impacts', 'environmental impact', 'animal welfare', 'health concerns', 'cultural and social norms', 'economic implications', 'genetics', 'environmental factors', 'lifestyle choices', 'exposure to radiation', 'exposure to carcinogens', 'viral infections', 'age', 'health consequences', 'environmental factors', 'lifestyle choices', 'genetic predisposition'], 'factorsParsed': ['cultural and social norms', 'health concerns', 'availability and accessibility', 'dietary preferences and taste', 'environmental impact', 'Eating meat', 'Causes cancer'], 'edges': [['cultural and social norms', 'health concerns', 0.8], ['cultural and social norms', 'availability and accessibility', 0.8], ['cultural and social norms', 'dietary preferences and taste', 1.0], ['cultural and social norms', 'environmental impact', 0.8], ['cultural and social norms', 'Eating meat', 0.6], ['health concerns', 'cultural and social norms', 0.8], ['health concerns', 'availability and accessibility', 0.8], ['health concerns', 'dietary preferences and taste', 0.8], ['health concerns', 'Eating meat', 0.6], ['health concerns', 'Causes cancer', 0.6], ['availability and accessibility', 'cultural and social norms', 0.8], ['availability and accessibility', 'health concerns', 0.6], ['availability and accessibility', 'dietary preferences and taste', 0.8], ['availability and accessibility', 'environmental impact', 0.8], ['availability and accessibility', 'Eating meat', 0.6], ['dietary preferences and taste', 'cultural and social norms', 0.8], ['dietary preferences and taste', 'health concerns', 0.8], ['dietary preferences and taste', 'Eating meat', 0.6], ['environmental impact', 'cultural and social norms', 0.8], ['environmental impact', 'health concerns', 1.0], ['environmental impact', 'dietary preferences and taste', 0.6], ['environmental impact', 'Eating meat', 0.8], ['environmental impact', 'Causes cancer', 0.6], ['Eating meat', 'cultural and social norms', 0.6], ['Eating meat', 'health concerns', 0.6], ['Eating meat', 'availability and accessibility', 0.6], ['Eating meat', 'dietary preferences and taste', 0.8], ['Eating meat', 'environmental impact', 0.8], ['Eating meat', 'Causes cancer', 0.6], ['Causes cancer', 'cultural and social norms', 0.6], ['Causes cancer', 'health concerns', 0.6], ['Causes cancer', 'availability and accessibility', 0.6], ['Causes cancer', 'environmental impact', 0.6], ['Causes cancer', 'Eating meat', 0.6]]}]
net, cache = prompt_to_output_test(texts[0], caches[0])
print(cache)
net.display()
print('1')